# Generated by Django 5.0.6 on 2024-06-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohi', '0003_dataset_var_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='DataRecord',
        ),
    ]
